from firebase_admin import credentials, firestore

db = firestore.client()

class UserSerializer:
    def __init__(self, user_data):
        self.user_data = user_data

    def save(self):
        collection_name = 'user'

        # Save the JSON data to Firestore with autogenerated ID
        db.collection(collection_name).add(self.user_data)